# Generated by Django 4.2 on 2023-04-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65, verbose_name='feriado')),
                ('dia', models.IntegerField(verbose_name='data')),
                ('mes', models.IntegerField(verbose_name='mes')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='ultima alteracao foi em:')),
            ],
        ),
    ]
